on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 22.13.1 ref mise.toml
      uses: actions/setup-node@v2
      with:
        node-version: 22.13.1
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
